version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_net

  user_auth:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./keys:/app/keys
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db:5432/userdb
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh db:5432 -- python app/db/migrations/create_tables.py &&
        uvicorn app.main:app --host 0.0.0.0 --port 8080
    networks:
      - internal_net  
      - proxy_net
    deploy: 
      replicas: 3

  learningpath:
    build:
      context: ../learning_path_be
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    env_file:
      - ../learning_path_be/.env
    networks:
      - internal_net
      - proxy_net
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db:5432/userdb
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh db:5432 -- uvicorn app.main:app --host 0.0.0.0 --port 8090
    deploy: 
      replicas: 2

  lb-auth:
    image: nginx:1.25-alpine
    container_name: lb-auth
    restart: always
    volumes:
      - ./load-balancers/nginx-auth.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy_net 
    depends_on:
      - user_auth 

  lb-learningpath:
    image: nginx:1.25-alpine
    container_name: lb-learningpath
    restart: always
    volumes:
      - ./load-balancers/nginx-learningpath.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy_net 
    depends_on:
      - learningpath

  kong:
    image: kong:3.4
    container_name: kong
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    depends_on:
      - lb-auth
      - lb-learningpath
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong.yml:/kong/kong.yml:ro
    networks:
      - proxy_net

volumes:
  postgres_data:

networks:
  proxy_net:
    driver: bridge    
  internal_net:
    driver: bridge    